# This workflow will release the packages with Changesets
name: 'ğŸ”—ğŸš€ Release Package'

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: 'Do you want to create a release PR?'
        default: false
        required: true
  pull_request:
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    environment: prod-ap-southeast-2
    name: ğŸš€ Release
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' || (github.event_name ==
      'pull_request' && github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'changeset-release/main')
    outputs:
      published: ${{ steps.changesets.outputs.published }}

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          scope: '@subifinancial'

      - name: ğŸ§© Install Dependencies
        run: npm ci

      - name: ğŸ—ï¸ Build
        run: npm run build:prod
        env:
          SUBI_CONNECT_IMAGES_BASE_URL:
            ${{ secrets.SUBI_CONNECT_IMAGES_BASE_URL }}
          SUBI_CONNECT_PUBLIC_BASE_URL:
            ${{ secrets.SUBI_CONNECT_PUBLIC_BASE_URL }}
          SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL:
            ${{ secrets.SUBI_CONNECT_SANDBOX_PUBLIC_BASE_URL }}

      - name: ğŸ“£ Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: '[Automated] Version package ğŸ”—ğŸ¦‹'
          publish: npm run cs:publish
          commit: 'chore(release): version package ğŸ”—ğŸ¦‹'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  deploy-all-demos:
    name: ğŸš¢ Deploy new release to all demo environments
    needs: release
    if: needs.release.outputs.published == 'true'
    uses: ./.github/workflows/deploy-all-demos.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
