# This workflow will release the packages with Changesets
name: 'ğŸ”—ğŸš€ Release Package'

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: 'Do you want to create a release PR?'
        default: false
        required: true
  pull_request:
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: ğŸš€ Release
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' || (github.event_name ==
      'pull_request' && github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'changeset-release/main')

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          scope: '@subifinancial'

      - name: ğŸ§© Install Dependencies
        run: npm ci

      - name: ğŸ—ï¸ Build
        run: npm run build:prod

      - name: ğŸ“£ Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: '[Automated] Version package ğŸ”—ğŸ¦‹'
          publish: npm run cs:publish
          commit: 'chore(release): version package ğŸ”—ğŸ¦‹'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
