# This workflow will release the packages with Changesets
name: 'ğŸ”—ğŸš€ Release Package'

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: 'Do you want to create a release PR?'
        default: false
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: ğŸš€ Release
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@subifinancial'

      - name: ğŸ§© Install Dependencies
        run: npm ci

      - name: ğŸ” 'Create env file'
        run: |
          touch .env.production
          echo SUBI_CONNECT_PUBLIC_BASE_URL=${{ secrets.SUBI_CONNECT_PUBLIC_BASE_URL }} >> .env.production

      - name: ğŸ—ï¸ Build
        run: npm run build:prod

      - name: ğŸ“£ Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: '[Automated] Version package ğŸ”—ğŸ¦‹'
          publish: npm run cs:publish
          commit: 'chore(release): version package ğŸ”—ğŸ¦‹'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
